AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: igad-innovation-hub - fullstack deployment

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      
      BinaryMediaTypes:
        - 'multipart/form-data'
        - 'application/pdf'
        - 'application/octet-stream'

  # Lambda Function with Web Adapter
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /Users/jcadavid/Desktop/DEV/Desarrollos/alliance-IGAD/igad-app/backend/dist
      Handler: bootstrap
      Runtime: python3.9
      MemorySize: 512
      Timeout: 300  # Increased from 120 to 300 seconds (5 minutes)
      Architectures:
        - x86_64
      Environment:
        Variables:
          PORT: 8080
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          COGNITO_CLIENT_ID: 7p11hp6gcklhctcr9qffne71vl
          COGNITO_USER_POOL_ID: us-east-1_IMi3kSuB8
          TABLE_NAME: igad-testing-main-table
          PROPOSALS_BUCKET: !Ref ProposalDocumentsBucket
          # VECTOR_BUCKET: !Ref VectorStorageBucket  # Uncomment when S3 Vector bucket is enabled
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:AdminRespondToAuthChallenge
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
                - cognito-idp:AdminDeleteUser
                - cognito-idp:AdminEnableUser
                - cognito-idp:AdminDisableUser
                - cognito-idp:AdminUpdateUserAttributes
                - cognito-idp:AdminAddUserToGroup
                - cognito-idp:AdminRemoveUserFromGroup
                - cognito-idp:AdminListGroupsForUser
                - cognito-idp:ListUsers
                - cognito-idp:ListGroups
                - cognito-idp:ForgotPassword
                - cognito-idp:ConfirmForgotPassword
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource: 
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/igad-testing-main-table'
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/igad-testing-main-table/index/*'
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub '${ProposalDocumentsBucket.Arn}/*'
                - !GetAtt ProposalDocumentsBucket.Arn
          
          
          
      
      Layers:
        
        - !Sub "arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:25"
        
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/{proxy+}
            Method: ANY
        RootApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api
            Method: ANY
        DocsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /docs
            Method: GET
        RedocEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /redoc
            Method: GET
        OpenApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /openapi.json
            Method: GET
        RootCatchAllEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  

  # S3 bucket for website content
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # CloudFront Origin Access Control
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket policy for CloudFront access
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"

  # CloudFront distribution
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: !Sub "${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
            Id: ApiOrigin
            OriginPath: "/prod"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          # SPA routing support
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RouterFunction.FunctionARN
        CacheBehaviors:
          - PathPattern: "/api/*"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: true
              Headers: ["Authorization"]
              Cookies:
                Forward: all
            # Disable caching for API requests
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        

  # CloudFront Function for routing
  RouterFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-router-function"
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Don't rewrite API requests
          if (uri.startsWith('/api/')) {
            return request;
          }

          // Don't rewrite requests for static assets (files with extensions)
          if (uri.includes('.') && !uri.endsWith('/')) {
            return request;
          }

          // Only rewrite requests that look like routes (no file extension)
          if (!uri.includes('.') || uri.endsWith('/')) {
            request.uri = '/index.html';
          }

          return request;
        }
      FunctionConfig:
        Comment: "Rewrite requests for frontend routing"
        Runtime: cloudfront-js-1.0

  # S3 Bucket for Proposal Documents and Vectors
  ProposalDocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'igad-proposal-documents-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Express One Zone Bucket for Vector Storage (Future Implementation)
  # Note: Uncomment when ready to use S3 Vector metadata buckets
  # VectorStorageBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub 'igad-vectors--use1-az4--x-s3'
  #     # S3 Express One Zone configuration
  #     # DataRedundancy: SingleAvailabilityZone
  #     # Type: Directory
  #     # LocationName: !Sub '${AWS::Region}az4'
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"

  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ApiFunction.Arn

  FunctionName:
    Description: Lambda function name
    Value: !Ref ApiFunction

  

  WebsiteBucket:
    Description: S3 bucket for website content
    Value: !Ref WebsiteBucket

  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !Sub "https://${WebsiteDistribution.DomainName}"

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref WebsiteDistribution

  ProposalDocumentsBucket:
    Description: S3 bucket for proposal documents and vectors
    Value: !Ref ProposalDocumentsBucket
